version: "2"

volumes:
  db_data: {}

services:
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: mysql
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
      ports:
       - "3308:3306"
    volumes:
      - db_data:/var/lib/mysql/data
