version: "3.1"
volumes:
  db_data: {}

services:
    webserver:
      image: nginx:alpine
      container_name: nginx-webserver
      working_dir: /application
      volumes:
          - ../:/application
          - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8080:80"
      depends_on:
       - "php-fpm"

    php-fpm:
      build: php-fpm
      container_name: nginx-php-fpm
      working_dir: /application
      volumes:
        - ../:/application
        - ./php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini

    memory_database:
      image: mariadb
      environment:
        MYSQL_ROOT_PASSWORD: admin
        MYSQL_DATABASE: mysql
        MYSQL_USER: mysql
        MYSQL_PASSWORD: mysql
        MYSQL_DATABASE: database_test
      ports:
       - "3307:3306"
      tmpfs: /var/lib/mysql:rw

    disk_database:
      image: mariadb
      environment:
        MYSQL_ROOT_PASSWORD: admin
        MYSQL_DATABASE: mysql
        MYSQL_USER: mysql
        MYSQL_PASSWORD: mysql
        MYSQL_DATABASE: database_dev
      ports:
       - "3308:3306"
      volumes:
        - db_data:/var/lib/mysql/data

    npm:
      build: npm
      container_name: npm
      working_dir: /application
      volumes:
        - ../:/application
      
