version: "2"

services:
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: mysql
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
      MYSQL_DATABASE: iris2_test
      ports:
       - "3307:3306"
    tmpfs: /var/lib/mysql:rw
